// modal actions
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export type TOGGLE_LOADING_TYPE = 'TOGGLE_LOADING';

export const TOGGLE_APP_MODAL = 'TOGGLE_APP_MODAL';
export type TOGGLE_APP_MODAL_TYPE = 'TOGGLE_APP_MODAL';

// userObject actions
export const UPDATE_LOCAL_USER_OBJECT = 'UPDATE_LOCAL_USER_OBJECT';
export type UPDATE_LOCAL_USER_OBJECT_TYPE = 'UPDATE_LOCAL_USER_OBJECT';
